# $baseUrl = https://webhook.site/c6139b56-66dc-41de-9752-30fe85a27251
#
# POST with bearer auth
# :nombre = Kenji
# :metodo = post
POST $baseUrl/:metodo
Content-type: application/json
Authorization: Bearer aslkdfjweafoieqjfoieqjfoiqwjfq
{
    "nombre": ':nombre'
}

# PATCH with user/pw auth
# :nombre = Martin
# :metodo = patch
PATCH $baseUrl/:metodo
Content-type: application/json
php-auth-user: pepito # for user / pw
php-auth-pw: lopez
{
    "nombre": ':nombre'
}


# GET with user/pw auth
# :nombre = Martin
# :metodo = get
# :nombre = kenji
# :apellido = ushiro
GET $baseUrl/:metodo?nombre=:nombre&apellido=:apellido
Content-type: application/json
php-auth-user: pepito # for user / pw
php-auth-pw: lopez

# GET localhost
GET http://localhost:1591/
