vim.keymap.set("n", "gd", ":lua vim.lsp.buf.definition()<CR>")
vim.keymap.set("n", "gD", ":lua vim.lsp.buf.declaration()<CR>")
vim.keymap.set("n", "gy", ":lua vim.lsp.buf.type_definition()<CR>")
vim.keymap.set("n", "gr", ":Lspsaga finder<CR>")
vim.keymap.set("n", "gi", ":lua vim.lsp.buf.implementation()<CR>")
vim.keymap.set("n", "<leader>lh", ":lua vim.lsp.buf.signature_help()<CR>")
vim.keymap.set("n", "<leader>lk", ":lua vim.lsp.buf.signature_help()<CR>")
vim.keymap.set("n", "<leader>la", ":Lspsaga code_action<CR>")
vim.keymap.set("n", "<leader>lc", ":lua vim.diagnostic.hide()<CR>")
vim.keymap.set("n", "<leader>lA", ":Telescope lsp_range_code_actions<CR>")
vim.keymap.set("n", "<leader>ld", ":Telescope diagnostics bufnr=0<CR>")
vim.keymap.set("n", "<leader>lD", ":Telescope diagnostics<CR>")
vim.keymap.set("n", "<leader>lr", ":Lspsaga rename<CR>")
vim.keymap.set("n", "<leader>lo", ":Lspsaga outline<CR>")
vim.keymap.set("n", "<leader>ls", ":Telescope lsp_document_symbols<CR>")
vim.keymap.set("n", "<leader>lS", ":Telescope lsp_workspace_symbols<CR>")
vim.keymap.set("n", "<leader>lf", ":lua vim.lsp.buf.formatting()<CR>")
vim.keymap.set("n", "<leader>lp", ":Lspsaga preview_definition<CR>")
vim.keymap.set("n", "<leader>ll", ":Lspsaga show_line_diagnostics<CR>")
vim.keymap.set("n", "<c-p>", ":Lspsaga diagnostic_jump_prev<CR>")
vim.keymap.set("n", "<c-n>", ":Lspsaga diagnostic_jump_next<CR>")
vim.keymap.set("n", "<leader>l,s", [[:LspStop <C-R>=<CR>]], { silent = false })
